### ISSUE TITLE
Update ACE highlighting

### ISSUE THREAD

**Issue by zbraniecki** [projectfluent/projectfluent.github.io#2]
I'd like to change how the highlighting works. I believe that red as the color for text is confusing as usually syntax highlighting uses red when something is wrong.

I'd like to suggest:
* message ID to be purple
* text to be black
* placeables to be dark blue
* variables to be  green
* message references to be purple
* variant keywords to be dark blue

@stasm what do you think?

**Comment by stasm** [comment]
There are two different things here: highlighting mode and a theme.  I'll need to update the mode for FTL 0.2 and 0.3 to make it recognize all productions correctly.

As far as the theme goes, the website currently uses the `github` theme which is very minimal and uses black for everything except strings and comments.  I like the simplicity and I'd prefer to not introduce any more colors. I also like that black is being used for syntax constructs.

I don't share your concern about red being confusing but I'm open to experimenting with other colors. Maybe blue?

![screenshot_2017-02-14_11-33-02](https://cloud.githubusercontent.com/assets/265818/22925574/8ad9deba-f2a9-11e6-8eee-2456d89db189.png)

**Comment by stasm** [comment]
I changed the text to blue in https://github.com/projectfluent/projectfluent.github.io/commit/9b2d9f4e0d897b0ac565008d549b026f916e855f.

I'm going to close this issue but here are my next steps: I'll publish the editor component from the website so that we can use it in projectfluent/play as well. I'll update the highlighting mode to FTL 0.2 and then we can revisit the color choices for a new theme.
